-- file_description: SQLite database initialization script for hazo_auth
-- This script creates all required tables for the hazo_auth authentication system
-- Compatible with SQLite (converted from PostgreSQL schema)

-- ============================================
-- hazo_auth Database Setup Script (SQLite)
-- ============================================

-- 1. Create users table
-- Note: SQLite doesn't support ENUM types, using TEXT with CHECK constraint
-- Note: SQLite doesn't have gen_random_uuid(), UUID will be generated by application
CREATE TABLE IF NOT EXISTS hazo_users (
    id TEXT PRIMARY KEY,
    email_address TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT,
    email_verified INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    login_attempts INTEGER NOT NULL DEFAULT 0,
    last_logon TEXT,
    profile_picture_url TEXT,
    profile_source TEXT CHECK (profile_source IN ('gravatar', 'custom', 'predefined')),
    mfa_secret TEXT,
    url_on_logon TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_hazo_users_email ON hazo_users(email_address);

-- 2. Create refresh tokens table
CREATE TABLE IF NOT EXISTS hazo_refresh_tokens (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES hazo_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    token_type TEXT NOT NULL DEFAULT 'refresh' CHECK (token_type IN ('refresh', 'password_reset', 'email_verification')),
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_hazo_refresh_tokens_user_id ON hazo_refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_refresh_tokens_token_type ON hazo_refresh_tokens(token_type);
CREATE INDEX IF NOT EXISTS idx_hazo_refresh_tokens_user_type ON hazo_refresh_tokens(user_id, token_type);

-- 3. Create permissions table
CREATE TABLE IF NOT EXISTS hazo_permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    permission_name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 4. Create roles table
CREATE TABLE IF NOT EXISTS hazo_roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role_name TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 5. Create role-permissions junction table
CREATE TABLE IF NOT EXISTS hazo_role_permissions (
    role_id INTEGER NOT NULL REFERENCES hazo_roles(id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES hazo_permissions(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (role_id, permission_id)
);
CREATE INDEX IF NOT EXISTS idx_hazo_role_permissions_role_id ON hazo_role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_hazo_role_permissions_permission_id ON hazo_role_permissions(permission_id);

-- 6. Create user-roles junction table
CREATE TABLE IF NOT EXISTS hazo_user_roles (
    user_id TEXT NOT NULL REFERENCES hazo_users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES hazo_roles(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_hazo_user_roles_user_id ON hazo_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_user_roles_role_id ON hazo_user_roles(role_id);

-- ============================================
-- hazo_chat Table (Chat Messages)
-- ============================================

-- 7. Create chat messages table
CREATE TABLE IF NOT EXISTS hazo_chat (
    id TEXT PRIMARY KEY,
    reference_id TEXT NOT NULL,
    reference_type TEXT NOT NULL,
    sender_user_id TEXT NOT NULL REFERENCES hazo_users(id),
    receiver_user_id TEXT NOT NULL REFERENCES hazo_users(id),
    message_text TEXT,
    reference_list TEXT,
    read_at TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_reference_id ON hazo_chat(reference_id);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_sender ON hazo_chat(sender_user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_receiver ON hazo_chat(receiver_user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_created_at ON hazo_chat(created_at);

-- ============================================
-- Optional: Insert default test data
-- ============================================

-- Insert a test user (password: 'password123' - bcrypt hash)
-- Note: In production, generate proper UUIDs and password hashes
INSERT OR IGNORE INTO hazo_users (id, email_address, password_hash, name, email_verified, is_active)
VALUES (
    'test-user-001',
    'test@example.com',
    '$2b$10$EpRnTzVlqHNP0.fUbXUwSOyuiXe/QLSUG6xNekdHgTGmrpHEfIoxm',
    'Test User',
    1,
    1
);

-- Insert default roles
INSERT OR IGNORE INTO hazo_roles (role_name) VALUES ('admin');
INSERT OR IGNORE INTO hazo_roles (role_name) VALUES ('user');

-- Insert default permissions
INSERT OR IGNORE INTO hazo_permissions (permission_name, description) 
VALUES ('admin_user_management', 'Ability to manage users');
INSERT OR IGNORE INTO hazo_permissions (permission_name, description) 
VALUES ('admin_role_management', 'Ability to manage roles and permissions');

-- Assign all permissions to admin role
INSERT OR IGNORE INTO hazo_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM hazo_roles r, hazo_permissions p WHERE r.role_name = 'admin';

-- Assign admin role to test user
INSERT OR IGNORE INTO hazo_user_roles (user_id, role_id)
SELECT 'test-user-001', id FROM hazo_roles WHERE role_name = 'admin';

-- ============================================
-- Done!
-- ============================================

