-- file_description: SQLite database initialization script for hazo_auth and hazo_chat
-- This script creates all required tables for hazo_auth v5.x and hazo_chat v3.x
-- Compatible with SQLite (converted from PostgreSQL schema)

-- ============================================
-- hazo_auth v5.x + hazo_chat v3.x Database Setup Script (SQLite)
-- ============================================

-- 1. Create users table
-- Note: SQLite doesn't support ENUM types, using TEXT with CHECK constraint
-- Note: SQLite doesn't have gen_random_uuid(), UUID will be generated by application
CREATE TABLE IF NOT EXISTS hazo_users (
    id TEXT PRIMARY KEY,
    email_address TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT,
    email_verified INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    login_attempts INTEGER NOT NULL DEFAULT 0,
    last_logon TEXT,
    profile_picture_url TEXT,
    profile_source TEXT CHECK (profile_source IN ('gravatar', 'custom', 'predefined')),
    mfa_secret TEXT,
    url_on_logon TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_hazo_users_email ON hazo_users(email_address);

-- 2. Create refresh tokens table
CREATE TABLE IF NOT EXISTS hazo_refresh_tokens (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES hazo_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    token_type TEXT NOT NULL DEFAULT 'refresh' CHECK (token_type IN ('refresh', 'password_reset', 'email_verification')),
    expires_at TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_hazo_refresh_tokens_user_id ON hazo_refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_refresh_tokens_token_type ON hazo_refresh_tokens(token_type);
CREATE INDEX IF NOT EXISTS idx_hazo_refresh_tokens_user_type ON hazo_refresh_tokens(user_id, token_type);

-- 3. Create permissions table
CREATE TABLE IF NOT EXISTS hazo_permissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    permission_name TEXT NOT NULL UNIQUE,
    description TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 4. Create roles table
CREATE TABLE IF NOT EXISTS hazo_roles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    role_name TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- 5. Create role-permissions junction table
CREATE TABLE IF NOT EXISTS hazo_role_permissions (
    role_id INTEGER NOT NULL REFERENCES hazo_roles(id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES hazo_permissions(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (role_id, permission_id)
);
CREATE INDEX IF NOT EXISTS idx_hazo_role_permissions_role_id ON hazo_role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_hazo_role_permissions_permission_id ON hazo_role_permissions(permission_id);

-- 6. Create user-roles junction table
CREATE TABLE IF NOT EXISTS hazo_user_roles (
    user_id TEXT NOT NULL REFERENCES hazo_users(id) ON DELETE CASCADE,
    role_id INTEGER NOT NULL REFERENCES hazo_roles(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, role_id)
);
CREATE INDEX IF NOT EXISTS idx_hazo_user_roles_user_id ON hazo_user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_user_roles_role_id ON hazo_user_roles(role_id);

-- ============================================
-- hazo_auth v5.x Scope System (Multi-Tenancy)
-- ============================================

-- 7. Create scopes table (replaces 8 separate org/scope tables in v4.x)
CREATE TABLE IF NOT EXISTS hazo_scopes (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    level TEXT NOT NULL CHECK (level IN ('firm', 'division', 'department', 'team', 'project', 'group', 'custom')),
    parent_scope_id TEXT REFERENCES hazo_scopes(id) ON DELETE SET NULL,
    slug TEXT,
    logo_url TEXT,
    primary_color TEXT,
    secondary_color TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_hazo_scopes_level ON hazo_scopes(level);
CREATE INDEX IF NOT EXISTS idx_hazo_scopes_parent ON hazo_scopes(parent_scope_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_hazo_scopes_slug ON hazo_scopes(slug) WHERE slug IS NOT NULL;

-- 8. Create user-scopes junction table (membership-based)
CREATE TABLE IF NOT EXISTS hazo_user_scopes (
    user_id TEXT NOT NULL REFERENCES hazo_users(id) ON DELETE CASCADE,
    scope_id TEXT NOT NULL REFERENCES hazo_scopes(id) ON DELETE CASCADE,
    role_id TEXT NOT NULL REFERENCES hazo_roles(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, scope_id)
);
CREATE INDEX IF NOT EXISTS idx_hazo_user_scopes_user ON hazo_user_scopes(user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_user_scopes_scope ON hazo_user_scopes(scope_id);
CREATE INDEX IF NOT EXISTS idx_hazo_user_scopes_role ON hazo_user_scopes(role_id);

-- 9. Create scope invitations table
CREATE TABLE IF NOT EXISTS hazo_scope_invitations (
    id TEXT PRIMARY KEY,
    email_address TEXT NOT NULL,
    scope_id TEXT NOT NULL REFERENCES hazo_scopes(id) ON DELETE CASCADE,
    role_id TEXT NOT NULL REFERENCES hazo_roles(id) ON DELETE CASCADE,
    invited_by_user_id TEXT NOT NULL REFERENCES hazo_users(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    accepted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_hazo_scope_invitations_email ON hazo_scope_invitations(email_address);
CREATE INDEX IF NOT EXISTS idx_hazo_scope_invitations_scope ON hazo_scope_invitations(scope_id);
CREATE INDEX IF NOT EXISTS idx_hazo_scope_invitations_token ON hazo_scope_invitations(token_hash);

-- ============================================
-- hazo_chat v3.x Group-Based Chat System
-- ============================================

-- 10. Create chat groups table (v3.x - group-based chat)
CREATE TABLE IF NOT EXISTS hazo_chat_group (
    id TEXT PRIMARY KEY,
    client_user_id TEXT REFERENCES hazo_users(id),
    group_type TEXT NOT NULL DEFAULT 'support' CHECK (group_type IN ('support', 'peer', 'group')),
    name TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_group_client ON hazo_chat_group(client_user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_group_type ON hazo_chat_group(group_type);

-- 11. Create chat group users (membership and roles)
CREATE TABLE IF NOT EXISTS hazo_chat_group_users (
    chat_group_id TEXT NOT NULL REFERENCES hazo_chat_group(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL REFERENCES hazo_users(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('client', 'staff', 'owner', 'admin', 'member')),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (chat_group_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_group_users_user ON hazo_chat_group_users(user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_group_users_group ON hazo_chat_group_users(chat_group_id);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_group_users_role ON hazo_chat_group_users(role);

-- 12. Create chat messages table (v3.x - updated for group chat)
CREATE TABLE IF NOT EXISTS hazo_chat (
    id TEXT PRIMARY KEY,
    reference_id TEXT NOT NULL,
    reference_type TEXT DEFAULT 'chat',
    sender_user_id TEXT NOT NULL REFERENCES hazo_users(id),
    chat_group_id TEXT NOT NULL REFERENCES hazo_chat_group(id),
    message_text TEXT,
    reference_list TEXT,
    read_at TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    changed_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_reference_id ON hazo_chat(reference_id);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_sender ON hazo_chat(sender_user_id);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_group ON hazo_chat(chat_group_id);
CREATE INDEX IF NOT EXISTS idx_hazo_chat_created_at ON hazo_chat(created_at);

-- ============================================
-- Optional: Insert default test data
-- ============================================

-- Insert default roles
INSERT OR IGNORE INTO hazo_roles (id, role_name) VALUES ('role-admin-001', 'admin');
INSERT OR IGNORE INTO hazo_roles (id, role_name) VALUES ('role-user-001', 'user');
INSERT OR IGNORE INTO hazo_roles (id, role_name) VALUES ('role-staff-001', 'staff');

-- Insert default permissions
INSERT OR IGNORE INTO hazo_permissions (permission_name, description)
VALUES ('admin_user_management', 'Ability to manage users');
INSERT OR IGNORE INTO hazo_permissions (permission_name, description)
VALUES ('admin_role_management', 'Ability to manage roles and permissions');
INSERT OR IGNORE INTO hazo_permissions (permission_name, description)
VALUES ('admin_scope_management', 'Ability to manage scopes and invitations');

-- Assign all permissions to admin role
INSERT OR IGNORE INTO hazo_role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM hazo_roles r, hazo_permissions p WHERE r.role_name = 'admin';

-- Insert test users (password: 'password123' - bcrypt hash)
INSERT OR IGNORE INTO hazo_users (id, email_address, password_hash, name, email_verified, is_active)
VALUES (
    'test-user-001',
    'test@example.com',
    '$2b$10$EpRnTzVlqHNP0.fUbXUwSOyuiXe/QLSUG6xNekdHgTGmrpHEfIoxm',
    'Test User',
    1,
    1
);

INSERT OR IGNORE INTO hazo_users (id, email_address, password_hash, name, email_verified, is_active)
VALUES (
    'test-user-002',
    'staff@example.com',
    '$2b$10$EpRnTzVlqHNP0.fUbXUwSOyuiXe/QLSUG6xNekdHgTGmrpHEfIoxm',
    'Staff User',
    1,
    1
);

-- Create test scope (firm)
INSERT OR IGNORE INTO hazo_scopes (id, name, level, slug)
VALUES (
    'scope-test-firm-001',
    'Test Firm',
    'firm',
    'test-firm'
);

-- Assign users to scope with roles
INSERT OR IGNORE INTO hazo_user_scopes (user_id, scope_id, role_id)
VALUES ('test-user-001', 'scope-test-firm-001', 'role-admin-001');

INSERT OR IGNORE INTO hazo_user_scopes (user_id, scope_id, role_id)
VALUES ('test-user-002', 'scope-test-firm-001', 'role-staff-001');

-- Create test chat group
INSERT OR IGNORE INTO hazo_chat_group (id, client_user_id, group_type, name)
VALUES (
    'chat-group-001',
    'test-user-001',
    'support',
    'Test Support Chat'
);

-- Add users to chat group
INSERT OR IGNORE INTO hazo_chat_group_users (chat_group_id, user_id, role)
VALUES ('chat-group-001', 'test-user-001', 'client');

INSERT OR IGNORE INTO hazo_chat_group_users (chat_group_id, user_id, role)
VALUES ('chat-group-001', 'test-user-002', 'staff');

-- ============================================
-- Done!
-- ============================================

